### PR TITLE
Fix firebase plugins compatibility: update build.gradle for play services 15+

### PR DESCRIPTION
**Pull request by aidandavis**

### CODE REVIEW

**Comment by acrozes** [comment]
@lukaspili can you merge this request to fix "Crashing after integration geolocation"

**Comment by jobel-code** [comment]
Yes. Please, update!

**Comment by Carrein** [comment]
I tried forking the repo and applying the fix manually but still can't seem to get this to work. This is tested on a fresh flutter project with default settings.

Dependencies:
```
  firebase_auth: ^0.5.11
  geolocation:
    git:
      url: git@github.com:Carrein/geolocation.git
```

Changes made can be seen on my forked [repo](https://github.com/loup-v/geolocation/compare/master...Carrein:master).

**Comment by lukaspili** [comment]
Sorry for the delay. It should be fixed in the latest release 1.0.0.

**Pull request closed without merging**
