### PR TITLE
Fix firebase plugins compatibility

### PR DESCRIPTION
**Pull request by jobel-code**
Fixes issues #31 .

### CODE REVIEW

**Comment by aidandavis** [comment]
#16 - I've made the same pull request over two months ago. Haven't heard anything from the developer.

**Comment by jobel-code** [comment]
Hope we will hear from them soon, and they  take your pull request first and discard mine. ;)

**Comment by aidandavis** [comment]
I've found these two forks of this repo that are being updated. I haven't tested them though, they may be just updated for their own purposes. Could be helpful.
[LJaraCastillo](https://github.com/LJaraCastillo/geolocation)
[videah](https://github.com/videah/geolocation)

**Comment by rafalbednarczuk** [comment]
it's easy fix but It's so desired

**Comment by lukaspili** [comment]
Sorry for the details. This should be fixed in 1.0.0.

**Pull request closed without merging**
